from html import escape
from pathlib import Path

from .models import Event


def generate_html(events: list[Event], path: str, area: str) -> None:
    sorted_events = sorted(
        events,
        key=lambda event: (
            event.numerical_month if event.numerical_month is not None else 99,
            event.numerical_date if event.numerical_date is not None else 99,
            event.date,
        ),
    )

    dated_events = [
        event
        for event in sorted_events
        if event.numerical_month is not None
        and event.numerical_date is not None
    ]

    month_names = {
        1: "January",
        2: "February",
        3: "March",
        4: "April",
        5: "May",
        6: "June",
        7: "July",
        8: "August",
        9: "September",
        10: "October",
        11: "November",
        12: "December",
    }

    if len(dated_events) >= 2:
        first_event = dated_events[0]
        last_event = dated_events[-1]

        time_span = (
            f"{month_names.get(first_event.numerical_month, str(first_event.numerical_month))} "
            f"{first_event.numerical_date} – "
            f"{month_names.get(last_event.numerical_month, str(last_event.numerical_month))} "
            f"{last_event.numerical_date}"
        )
    elif len(dated_events) == 1:
        only_event = dated_events[0]

        time_span = (
            f"{month_names.get(only_event.numerical_month, str(only_event.numerical_month))} "
            f"{only_event.numerical_date}"
        )
    else:
        time_span = "Time span unavailable"

    all_genres = sorted(
        {
            genre.strip()
            for event in sorted_events
            for genre in event.band_genre
            if genre.strip()
        },
        key=str.lower,
    )

    all_detailed_genres = sorted(
        {
            genre.strip()
            for event in sorted_events
            for genre in event.detailed_genre
            if genre.strip()
        },
        key=str.lower,
    )

    def render_genres(
        genres: list[str],
        *,
        empty_text: str,
        tag_class: str = "",
    ) -> str:
        cleaned_genres = [
            genre.strip()
            for genre in genres
            if genre.strip()
        ]

        if not cleaned_genres:
            return f'<span class="muted">{escape(empty_text)}</span>'

        class_name = "genre-tag"

        if tag_class:
            class_name += f" {tag_class}"

        return "".join(
            f'<span class="{class_name}">{escape(genre)}</span>'
            for genre in cleaned_genres
        )

    def render_genre_filters(
        genres: list[str],
        *,
        filter_type: str,
    ) -> str:
        if not genres:
            return '<span class="muted">No filters available</span>'

        return "".join(
            f"""
            <span class="filter-chip-group">
                <button
                    class="filter-chip include-chip"
                    type="button"
                    data-filter-mode="include"
                    data-filter-type="{escape(filter_type)}"
                    data-genre="{escape(genre.lower())}"
                    title="Include {escape(genre)}"
                    aria-label="Include {escape(genre)}"
                >
                    + {escape(genre)}
                </button>

                <button
                    class="filter-chip exclude-chip"
                    type="button"
                    data-filter-mode="exclude"
                    data-filter-type="{escape(filter_type)}"
                    data-genre="{escape(genre.lower())}"
                    title="Exclude {escape(genre)}"
                    aria-label="Exclude {escape(genre)}"
                >
                    −
                </button>
            </span>
            """
            for genre in genres
        )

    def render_must_see(event: Event) -> str:
        if event.must_see is True:
            return """
            <span class="must-see-badge must-see-yes">
                ★ Must-see
            </span>
            """

        if event.must_see is False:
            return """
            <span class="must-see-badge must-see-no">
                Not must-see
            </span>
            """

        return """
        <span class="must-see-badge must-see-unknown">
            Must-see not rated
        </span>
        """

    def render_event(event: Event) -> str:
        warning_html = ""

        if event.band_details_trustworthy is False:
            warning_html = """
            <div class="warning">
                ⚠️ Genre and info were generated by an LLM. This entry is
                likely incorrect, so please double-check it.
            </div>
            """

        band_info = (
            escape(event.band_info)
            if event.band_info.strip()
            else '<span class="muted">No band info available</span>'
        )

        genre_data = "|".join(
            genre.strip().lower()
            for genre in event.band_genre
            if genre.strip()
        )

        detailed_genre_data = "|".join(
            genre.strip().lower()
            for genre in event.detailed_genre
            if genre.strip()
        )

        if event.must_see is True:
            must_see_data = "true"
        elif event.must_see is False:
            must_see_data = "false"
        else:
            must_see_data = "unknown"

        return f"""
        <article
            class="event-card"
            data-genres="{escape(genre_data)}"
            data-detailed-genres="{escape(detailed_genre_data)}"
            data-must-see="{must_see_data}"
        >
            <div class="event-header">
                <div class="event-title-area">
                    <div class="event-title-row">
                        <h2>{escape(event.band)}</h2>
                        {render_must_see(event)}
                    </div>

                    <p class="venue">{escape(event.venue)}</p>
                </div>

                <a
                    class="event-link"
                    href="{escape(event.link)}"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    View event
                </a>
            </div>

            <p class="date">☽ {escape(event.date)}</p>

            <div class="genre-section">
                <p class="genre-label">Genre</p>

                <div class="genres">
                    {render_genres(
                        event.band_genre,
                        empty_text="No genre info",
                    )}
                </div>
            </div>

            <div class="genre-section detailed-genre-section">
                <p class="genre-label">Detailed genre</p>

                <div class="genres">
                    {render_genres(
                        event.detailed_genre,
                        empty_text="No detailed genre info",
                        tag_class="detailed-genre-tag",
                    )}
                </div>
            </div>

            <p class="band-info">{band_info}</p>

            {warning_html}
        </article>
        """

    events_html = "\n".join(
        render_event(event)
        for event in sorted_events
    )

    genre_filters_html = render_genre_filters(
        all_genres,
        filter_type="genre",
    )

    detailed_genre_filters_html = render_genre_filters(
        all_detailed_genres,
        filter_type="detailed-genre",
    )

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />

    <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0"
    />

    <title>Upcoming Events</title>

    <style>
        * {{
            box-sizing: border-box;
        }}

        :root {{
            --ink: #26231f;
            --soft-ink: #5b534b;
            --muted-ink: #8a7f73;

            --paper: #eee7dc;
            --paper-deep: #e3d8c9;
            --card: #f8f1e7;
            --card-soft: #fbf7ef;

            --sepia: #8b6f47;
            --sepia-dark: #57452f;
            --ash-blue: #596877;
            --ash-blue-dark: #3e4a56;
            --wine: #7b3f48;
            --rust: #9a5a3c;

            --border: #cdbfae;
            --border-dark: #a9957f;
            --shadow: rgba(52, 43, 34, 0.15);
        }}

        body {{
            margin: 0;
            font-family: Georgia, "Times New Roman", Times, serif;
            background:
                radial-gradient(
                    circle at 12% 8%,
                    rgba(123, 63, 72, 0.16),
                    transparent 28rem
                ),
                radial-gradient(
                    circle at 84% 18%,
                    rgba(89, 104, 119, 0.18),
                    transparent 30rem
                ),
                linear-gradient(
                    180deg,
                    #d8cbbc 0%,
                    var(--paper) 34%,
                    #e9dfd2 100%
                );
            color: var(--ink);
            line-height: 1.58;
            font-size: 15px;
        }}

        body::before {{
            content: "";
            position: fixed;
            inset: 0;
            pointer-events: none;
            opacity: 0.28;
            background-image:
                linear-gradient(
                    rgba(70, 55, 40, 0.045) 1px,
                    transparent 1px
                ),
                linear-gradient(
                    90deg,
                    rgba(70, 55, 40, 0.035) 1px,
                    transparent 1px
                );
            background-size: 42px 42px;
        }}

        header {{
            position: relative;
            overflow: hidden;
            padding: 46px 20px 42px;
            background:
                linear-gradient(
                    135deg,
                    rgba(38, 35, 31, 0.96),
                    rgba(62, 74, 86, 0.94)
                ),
                radial-gradient(
                    circle at top,
                    rgba(205, 191, 174, 0.25),
                    transparent 28rem
                );
            color: #f4eadc;
            text-align: center;
            border-bottom: 1px solid rgba(205, 191, 174, 0.42);
            box-shadow: 0 18px 40px rgba(38, 35, 31, 0.18);
        }}

        header::after {{
            content: "";
            position: absolute;
            left: 50%;
            bottom: 20px;
            width: min(460px, 70vw);
            height: 1px;
            transform: translateX(-50%);
            background: linear-gradient(
                90deg,
                transparent,
                rgba(244, 234, 220, 0.55),
                transparent
            );
        }}

        header h1 {{
            position: relative;
            margin: 0;
            font-size: clamp(1.8rem, 4vw, 2.55rem);
            letter-spacing: 0.08em;
            font-weight: 500;
            text-transform: uppercase;
        }}

        header p {{
            position: relative;
            margin: 8px 0 0;
            color: #d6c9ba;
            font-size: 0.98rem;
            font-style: italic;
        }}

        .time-span {{
            position: relative;
            display: inline-flex;
            align-items: center;
            gap: 10px;
            margin-top: 18px;
            padding: 9px 18px;
            border-radius: 999px;
            color: #eadfce;
            background: rgba(244, 234, 220, 0.08);
            border: 1px solid rgba(244, 234, 220, 0.28);
            font-size: 0.9rem;
            font-style: italic;
            letter-spacing: 0.04em;
        }}

        .time-span::before,
        .time-span::after {{
            content: "✦";
            color: rgba(244, 234, 220, 0.58);
            font-size: 0.72rem;
        }}

        main {{
            max-width: 1180px;
            margin: 0 auto;
            padding: 34px 24px 64px;
        }}

        .toolbar {{
            background:
                linear-gradient(
                    180deg,
                    rgba(251, 247, 239, 0.95),
                    rgba(244, 236, 224, 0.94)
                );
            border: 1px solid var(--border);
            border-left: 4px solid var(--ash-blue);
            border-radius: 18px;
            padding: 22px;
            margin-bottom: 30px;
            box-shadow:
                0 16px 36px rgba(52, 43, 34, 0.10),
                inset 0 1px 0 rgba(255, 255, 255, 0.55);
        }}

        .toolbar-top {{
            display: flex;
            justify-content: space-between;
            align-items: center;
            gap: 16px;
            margin-bottom: 18px;
            padding-bottom: 13px;
            border-bottom: 1px solid rgba(169, 149, 127, 0.42);
        }}

        .toolbar h2 {{
            margin: 0;
            color: var(--sepia-dark);
            font-size: 1.05rem;
            line-height: 1.25;
            font-weight: 500;
            letter-spacing: 0.04em;
            text-transform: uppercase;
        }}

        .result-count {{
            margin: 0;
            color: var(--muted-ink);
            font-size: 0.92rem;
            white-space: nowrap;
            font-style: italic;
        }}

        .filter-section {{
            margin-top: 4px;
        }}

        .filter-heading {{
            margin: 0 0 10px;
            color: var(--soft-ink);
            font-size: 0.9rem;
            font-weight: 700;
            letter-spacing: 0.05em;
            text-transform: uppercase;
        }}

        .filter-row {{
            display: flex;
            flex-wrap: wrap;
            gap: 9px;
        }}

        .filter-chip-group {{
            display: inline-flex;
            align-items: stretch;
        }}

        .filter-chip,
        .clear-button,
        .must-see-filter {{
            appearance: none;
            border: 1px solid #c6b7a5;
            border-radius: 999px;
            background: rgba(248, 241, 231, 0.86);
            color: var(--sepia-dark);
            padding: 7px 12px;
            font-family: Georgia, "Times New Roman", Times, serif;
            font-size: 0.84rem;
            font-weight: 700;
            line-height: 1.25;
            cursor: pointer;
        }}

        .filter-chip:hover,
        .clear-button:hover,
        .must-see-filter:hover {{
            background: #ece1d2;
            color: var(--wine);
            border-color: var(--wine);
        }}

        .filter-chip-group .include-chip {{
            border-top-right-radius: 0;
            border-bottom-right-radius: 0;
        }}

        .filter-chip-group .exclude-chip {{
            border-top-left-radius: 0;
            border-bottom-left-radius: 0;
            margin-left: -1px;
            padding-inline: 10px;
        }}

        .filter-chip.include-active {{
            background: var(--ash-blue-dark);
            border-color: var(--ash-blue-dark);
            color: #f8f1e7;
        }}

        .filter-chip.exclude-active {{
            background: var(--wine);
            border-color: var(--wine);
            color: #f8f1e7;
        }}

        .filter-chip.include-active:hover {{
            background: var(--ash-blue-dark);
            border-color: var(--ash-blue-dark);
            color: #f8f1e7;
        }}

        .filter-chip.exclude-active:hover {{
            background: var(--wine);
            border-color: var(--wine);
            color: #f8f1e7;
        }}

        .must-see-filter-section {{
            margin-top: 18px;
            padding-top: 16px;
            border-top: 1px solid rgba(169, 149, 127, 0.42);
        }}

        .must-see-filter-row {{
            display: flex;
            flex-wrap: wrap;
            gap: 9px;
        }}

        .must-see-filter.active {{
            background: var(--ash-blue-dark);
            border-color: var(--ash-blue-dark);
            color: #f8f1e7;
        }}

        .must-see-filter.active:hover {{
            background: var(--ash-blue-dark);
            border-color: var(--ash-blue-dark);
            color: #f8f1e7;
        }}

        .filter-details {{
            margin-top: 18px;
            padding-top: 16px;
            border-top: 1px solid rgba(169, 149, 127, 0.42);
        }}

        .filter-details summary {{
            display: flex;
            align-items: center;
            gap: 8px;
            color: var(--soft-ink);
            font-size: 0.9rem;
            font-weight: 700;
            letter-spacing: 0.05em;
            text-transform: uppercase;
            cursor: pointer;
            list-style: none;
        }}

        .filter-details summary::-webkit-details-marker {{
            display: none;
        }}

        .filter-details summary::before {{
            content: "▸";
            display: inline-block;
            color: var(--wine);
            transition: transform 160ms ease;
        }}

        .filter-details[open] summary::before {{
            transform: rotate(90deg);
        }}

        .details-hint {{
            margin-left: auto;
            color: var(--muted-ink);
            font-size: 0.78rem;
            font-style: italic;
            font-weight: 400;
            letter-spacing: normal;
            text-transform: none;
        }}

        .filter-details[open] .details-hint {{
            display: none;
        }}

        .detailed-filter-row {{
            margin-top: 14px;
        }}

        .filter-actions {{
            display: flex;
            justify-content: flex-end;
            margin-top: 20px;
            padding-top: 16px;
            border-top: 1px solid rgba(169, 149, 127, 0.42);
        }}

        .clear-button {{
            background: rgba(255, 252, 246, 0.8);
            color: var(--muted-ink);
        }}

        .event-grid {{
            display: grid;
            grid-template-columns: repeat(
                auto-fit,
                minmax(420px, 1fr)
            );
            gap: 30px;
            align-items: start;
        }}

        .event-card {{
            position: relative;
            overflow: hidden;
            background:
                linear-gradient(
                    180deg,
                    rgba(251, 247, 239, 0.98),
                    rgba(246, 238, 226, 0.96)
                );
            border-radius: 18px;
            padding: 26px;
            box-shadow:
                0 18px 46px rgba(52, 43, 34, 0.12),
                0 2px 8px rgba(52, 43, 34, 0.06);
            border: 1px solid var(--border);
            border-top: 3px double var(--border-dark);
        }}

        .event-card::before {{
            content: "";
            position: absolute;
            top: 0;
            left: 22px;
            width: 1px;
            height: 100%;
            background: rgba(123, 63, 72, 0.16);
        }}

        .event-card::after {{
            content: "";
            position: absolute;
            inset: 10px;
            border: 1px solid rgba(169, 149, 127, 0.24);
            border-radius: 13px;
            pointer-events: none;
        }}

        .event-card:hover {{
            transform: translateY(-2px);
            box-shadow:
                0 26px 60px rgba(52, 43, 34, 0.16),
                0 4px 12px rgba(52, 43, 34, 0.08);
            transition: 160ms ease;
        }}

        .event-card.hidden {{
            display: none;
        }}

        .event-header {{
            position: relative;
            z-index: 1;
            display: flex;
            justify-content: space-between;
            gap: 18px;
            align-items: flex-start;
            margin-bottom: 16px;
            padding-left: 14px;
        }}

        .event-title-area {{
            min-width: 0;
        }}

        .event-title-row {{
            display: flex;
            flex-wrap: wrap;
            align-items: center;
            gap: 8px 10px;
        }}

        h2 {{
            margin: 0;
            font-size: 1.26rem;
            line-height: 1.25;
            letter-spacing: 0.01em;
            color: var(--ink);
            font-weight: 600;
        }}

        .venue {{
            margin: 7px 0 0;
            color: var(--soft-ink);
            font-weight: 700;
            line-height: 1.42;
        }}

        .must-see-badge {{
            display: inline-flex;
            align-items: center;
            flex: 0 0 auto;
            padding: 4px 9px;
            border-radius: 999px;
            font-size: 0.72rem;
            font-weight: 700;
            line-height: 1.3;
            white-space: nowrap;
        }}

        .must-see-yes {{
            background: rgba(154, 90, 60, 0.14);
            color: #75402e;
            border: 1px solid rgba(154, 90, 60, 0.38);
        }}

        .must-see-no {{
            background: rgba(89, 104, 119, 0.09);
            color: var(--ash-blue-dark);
            border: 1px solid rgba(89, 104, 119, 0.2);
        }}

        .must-see-unknown {{
            background: rgba(139, 111, 71, 0.08);
            color: var(--muted-ink);
            border: 1px dashed rgba(139, 111, 71, 0.32);
            font-style: italic;
            font-weight: 600;
        }}

        .date {{
            position: relative;
            z-index: 1;
            display: inline-flex;
            align-items: center;
            gap: 6px;
            margin: 0 0 16px 14px;
            padding: 7px 11px;
            border-radius: 999px;
            background: rgba(227, 216, 201, 0.58);
            color: var(--ash-blue-dark);
            border: 1px solid rgba(169, 149, 127, 0.56);
            font-size: 0.9rem;
            font-style: italic;
        }}

        .event-link {{
            flex: 0 0 auto;
            white-space: nowrap;
            text-decoration: none;
            background: var(--wine);
            color: #fbf4ea;
            padding: 9px 14px;
            border-radius: 999px;
            font-size: 0.82rem;
            font-weight: 750;
            box-shadow: 0 8px 18px rgba(123, 63, 72, 0.22);
            border: 1px solid rgba(255, 255, 255, 0.24);
        }}

        .event-link:hover {{
            background: #63323a;
        }}

        .genre-section {{
            position: relative;
            z-index: 1;
            margin: 2px 0 16px 14px;
        }}

        .detailed-genre-section {{
            margin-top: -4px;
        }}

        .genre-label {{
            margin: 0 0 7px;
            color: var(--muted-ink);
            font-size: 0.75rem;
            font-weight: 700;
            letter-spacing: 0.07em;
            text-transform: uppercase;
        }}

        .genres {{
            display: flex;
            flex-wrap: wrap;
            gap: 8px;
            margin: 0;
        }}

        .genre-tag {{
            display: inline-block;
            padding: 5px 10px;
            border-radius: 999px;
            background: rgba(89, 104, 119, 0.12);
            color: var(--ash-blue-dark);
            border: 1px solid rgba(89, 104, 119, 0.22);
            font-size: 0.79rem;
            font-weight: 700;
            line-height: 1.35;
        }}

        .detailed-genre-tag {{
            background: rgba(139, 111, 71, 0.11);
            color: var(--sepia-dark);
            border-color: rgba(139, 111, 71, 0.28);
        }}

        .band-info {{
            position: relative;
            z-index: 1;
            margin: 0;
            padding-left: 14px;
            color: var(--soft-ink);
            font-size: 0.93rem;
            line-height: 1.7;
        }}

        .warning {{
            position: relative;
            z-index: 1;
            margin: 18px 0 0 14px;
            padding: 12px 14px;
            border-radius: 14px;
            background: rgba(154, 90, 60, 0.10);
            border: 1px solid rgba(154, 90, 60, 0.38);
            color: #75402e;
            font-size: 0.84rem;
            font-weight: 700;
            line-height: 1.45;
        }}

        .muted {{
            color: var(--muted-ink);
            font-style: italic;
        }}

        .pagination {{
            display: flex;
            justify-content: center;
            align-items: center;
            gap: 12px;
            margin-top: 30px;
            flex-wrap: wrap;
        }}

        .pagination.hidden {{
            display: none;
        }}

        .pagination-button {{
            appearance: none;
            border: 1px solid var(--border-dark);
            border-radius: 999px;
            background: rgba(248, 241, 231, 0.9);
            color: var(--sepia-dark);
            padding: 8px 14px;
            font-family: Georgia, "Times New Roman", Times, serif;
            font-size: 0.86rem;
            font-weight: 700;
            cursor: pointer;
        }}

        .pagination-button:hover:not(:disabled) {{
            background: #ece1d2;
            color: var(--wine);
            border-color: var(--wine);
        }}

        .pagination-button:disabled {{
            cursor: not-allowed;
            opacity: 0.45;
        }}

        .page-info {{
            color: var(--soft-ink);
            font-size: 0.9rem;
            font-style: italic;
        }}

        .empty-state {{
            display: none;
            margin-top: 32px;
            padding: 30px;
            border-radius: 18px;
            background: rgba(251, 247, 239, 0.95);
            border: 1px dashed var(--border-dark);
            color: var(--muted-ink);
            text-align: center;
            font-size: 1rem;
            font-style: italic;
        }}

        .empty-state.visible {{
            display: block;
        }}

        @media (max-width: 960px) {{
            main {{
                max-width: 760px;
            }}

            .event-grid {{
                grid-template-columns: 1fr;
            }}
        }}

        @media (max-width: 560px) {{
            body {{
                font-size: 14px;
            }}

            header {{
                padding: 34px 16px 30px;
            }}

            main {{
                padding: 22px 14px 48px;
            }}

            .toolbar {{
                padding: 18px;
                border-radius: 16px;
            }}

            .toolbar-top {{
                flex-direction: column;
                align-items: flex-start;
                gap: 6px;
            }}

            .filter-details summary {{
                align-items: flex-start;
            }}

            .details-hint {{
                text-align: right;
            }}

            .filter-actions {{
                justify-content: flex-start;
            }}

            .event-card {{
                padding: 22px;
                border-radius: 16px;
            }}

            .event-card::before {{
                left: 16px;
            }}

            .event-header {{
                flex-direction: column;
                gap: 12px;
                padding-left: 8px;
            }}

            .event-link {{
                width: fit-content;
            }}

            .date,
            .genre-section,
            .band-info,
            .warning {{
                margin-left: 8px;
            }}

            .band-info {{
                padding-left: 0;
            }}

            .warning {{
                padding-left: 14px;
            }}

            h2 {{
                font-size: 1.16rem;
            }}

            .time-span {{
                font-size: 0.84rem;
                padding: 8px 14px;
            }}
        }}
    </style>
</head>

<body>
    <header>
        <h1>Upcoming Events in {escape(area)}</h1>

        <p>
            {len(sorted_events)}
            event{"s" if len(sorted_events) != 1 else ""}
        </p>

        <p>
            Content generated by LLM. Please double-check for correctness.
        </p>

        <div class="time-span">
            Time span: {escape(time_span)}
        </div>
    </header>

    <main>
        <section class="toolbar" aria-label="Event filters">
            <div class="toolbar-top">
                <h2>Filter events</h2>

                <p class="result-count">
                    Showing
                    <span id="visible-count">0</span>
                    of
                    <span id="filtered-count">{len(sorted_events)}</span>
                    matching events
                </p>
            </div>

            <div class="filter-section">
                <h3 class="filter-heading">Main Genre</h3>

                <div class="filter-row">
                    {genre_filters_html}
                </div>
            </div>

            <div class="must-see-filter-section">
                <h3 class="filter-heading">Must-see</h3>

                <div
                    class="must-see-filter-row"
                    role="group"
                    aria-label="Must-see filter"
                >
                    <button
                        class="must-see-filter active"
                        type="button"
                        data-must-see-filter="all"
                    >
                        All
                    </button>

                    <button
                        class="must-see-filter"
                        type="button"
                        data-must-see-filter="true"
                    >
                        ★ Must-see
                    </button>

                    <button
                        class="must-see-filter"
                        type="button"
                        data-must-see-filter="false"
                    >
                        Not must-see
                    </button>

                    <button
                        class="must-see-filter"
                        type="button"
                        data-must-see-filter="unknown"
                    >
                        Not rated
                    </button>
                </div>
            </div>

            <details class="filter-details">
                <summary>
                    <span>Detailed genre</span>
                    <span class="details-hint">Expand filters</span>
                </summary>

                <div class="filter-row detailed-filter-row">
                    {detailed_genre_filters_html}
                </div>
            </details>

            <div class="filter-actions">
                <button
                    class="clear-button"
                    type="button"
                    id="clear-filters"
                >
                    Show all
                </button>
            </div>
        </section>

        <section class="event-grid" id="event-grid">
            {events_html}
        </section>

        <nav
            class="pagination"
            id="pagination"
            aria-label="Event pages"
        >
            <button
                class="pagination-button"
                type="button"
                id="prev-page"
            >
                Previous
            </button>

            <span class="page-info" id="page-info">
                Page 1 of 1
            </span>

            <button
                class="pagination-button"
                type="button"
                id="next-page"
            >
                Next
            </button>
        </nav>

        <div class="empty-state" id="empty-state">
            No events match the selected filters.
        </div>
    </main>

    <script>
        const filterButtons = Array.from(
            document.querySelectorAll(".filter-chip")
        );

        const mustSeeButtons = Array.from(
            document.querySelectorAll(".must-see-filter")
        );

        const clearButton =
            document.getElementById("clear-filters");

        const cards = Array.from(
            document.querySelectorAll(".event-card")
        );

        const visibleCount =
            document.getElementById("visible-count");

        const filteredCount =
            document.getElementById("filtered-count");

        const pagination =
            document.getElementById("pagination");

        const prevPageButton =
            document.getElementById("prev-page");

        const nextPageButton =
            document.getElementById("next-page");

        const pageInfo =
            document.getElementById("page-info");

        const emptyState =
            document.getElementById("empty-state");

        const pageSize = 100;

        let currentPage = 1;

        const filterState = {{
            genre: {{
                included: new Set(),
                excluded: new Set(),
            }},
            "detailed-genre": {{
                included: new Set(),
                excluded: new Set(),
            }},
        }};

        let selectedMustSeeFilter = "all";

        function parseGenres(value) {{
            if (!value) {{
                return [];
            }}

            return value
                .split("|")
                .map((genre) => genre.trim())
                .filter(Boolean);
        }}

        function getCardGenres(card, filterType) {{
            if (filterType === "detailed-genre") {{
                return parseGenres(card.dataset.detailedGenres);
            }}

            return parseGenres(card.dataset.genres);
        }}

        function matchesFilterType(card, filterType) {{
            const genres = getCardGenres(card, filterType);
            const state = filterState[filterType];

            const matchesIncluded =
                state.included.size === 0 ||
                genres.some((genre) =>
                    state.included.has(genre)
                );

            const matchesExcluded =
                genres.some((genre) =>
                    state.excluded.has(genre)
                );

            return matchesIncluded && !matchesExcluded;
        }}

        function matchesMustSeeFilter(card) {{
            if (selectedMustSeeFilter === "all") {{
                return true;
            }}

            return card.dataset.mustSee === selectedMustSeeFilter;
        }}

        function cardMatchesActiveFilters(card) {{
            const matchesGenre =
                matchesFilterType(card, "genre");

            const matchesDetailedGenre =
                matchesFilterType(
                    card,
                    "detailed-genre"
                );

            const matchesMustSee =
                matchesMustSeeFilter(card);

            return (
                matchesGenre &&
                matchesDetailedGenre &&
                matchesMustSee
            );
        }}

        function updateEvents(resetPage = false) {{
            if (resetPage) {{
                currentPage = 1;
            }}

            const matchingCards =
                cards.filter(cardMatchesActiveFilters);

            const totalMatching = matchingCards.length;

            const totalPages = Math.max(
                1,
                Math.ceil(totalMatching / pageSize)
            );

            if (currentPage > totalPages) {{
                currentPage = totalPages;
            }}

            const startIndex =
                (currentPage - 1) * pageSize;

            const endIndex =
                startIndex + pageSize;

            const pageCards =
                matchingCards.slice(startIndex, endIndex);

            cards.forEach((card) => {{
                card.classList.add("hidden");
            }});

            pageCards.forEach((card) => {{
                card.classList.remove("hidden");
            }});

            visibleCount.textContent = pageCards.length;
            filteredCount.textContent = totalMatching;

            emptyState.classList.toggle(
                "visible",
                totalMatching === 0
            );

            pagination.classList.toggle(
                "hidden",
                totalMatching <= pageSize
            );

            pageInfo.textContent =
                `Page ${{currentPage}} of ${{totalPages}}`;

            prevPageButton.disabled =
                currentPage <= 1;

            nextPageButton.disabled =
                currentPage >= totalPages;
        }}

        function getPairedButton(
            mode,
            filterType,
            genre
        ) {{
            const pairedMode =
                mode === "include"
                    ? "exclude"
                    : "include";

            return filterButtons.find((button) => {{
                return (
                    button.dataset.filterMode === pairedMode &&
                    button.dataset.filterType === filterType &&
                    button.dataset.genre === genre
                );
            }});
        }}

        filterButtons.forEach((button) => {{
            button.addEventListener("click", () => {{
                const genre = button.dataset.genre;
                const mode = button.dataset.filterMode;
                const filterType =
                    button.dataset.filterType;

                if (
                    !genre ||
                    !mode ||
                    !filterType ||
                    !filterState[filterType]
                ) {{
                    return;
                }}

                const isInclude = mode === "include";
                const state = filterState[filterType];

                const activeSet = isInclude
                    ? state.included
                    : state.excluded;

                const oppositeSet = isInclude
                    ? state.excluded
                    : state.included;

                const activeClass = isInclude
                    ? "include-active"
                    : "exclude-active";

                const oppositeClass = isInclude
                    ? "exclude-active"
                    : "include-active";

                if (activeSet.has(genre)) {{
                    activeSet.delete(genre);
                    button.classList.remove(activeClass);
                }} else {{
                    activeSet.add(genre);
                    oppositeSet.delete(genre);
                    button.classList.add(activeClass);

                    const pairedButton =
                        getPairedButton(
                            mode,
                            filterType,
                            genre
                        );

                    if (pairedButton) {{
                        pairedButton.classList.remove(
                            oppositeClass
                        );
                    }}
                }}

                updateEvents(true);
            }});
        }});

        mustSeeButtons.forEach((button) => {{
            button.addEventListener("click", () => {{
                const value =
                    button.dataset.mustSeeFilter;

                if (!value) {{
                    return;
                }}

                selectedMustSeeFilter = value;

                mustSeeButtons.forEach((otherButton) => {{
                    otherButton.classList.toggle(
                        "active",
                        otherButton === button
                    );
                }});

                updateEvents(true);
            }});
        }});

        clearButton.addEventListener("click", () => {{
            Object.values(filterState).forEach(
                (state) => {{
                    state.included.clear();
                    state.excluded.clear();
                }}
            );

            selectedMustSeeFilter = "all";

            filterButtons.forEach((button) => {{
                button.classList.remove(
                    "include-active"
                );

                button.classList.remove(
                    "exclude-active"
                );
            }});

            mustSeeButtons.forEach((button) => {{
                button.classList.toggle(
                    "active",
                    button.dataset.mustSeeFilter === "all"
                );
            }});

            updateEvents(true);
        }});

        prevPageButton.addEventListener("click", () => {{
            if (currentPage > 1) {{
                currentPage -= 1;
                updateEvents();

                window.scrollTo({{
                    top: 0,
                    behavior: "smooth",
                }});
            }}
        }});

        nextPageButton.addEventListener("click", () => {{
            currentPage += 1;
            updateEvents();

            window.scrollTo({{
                top: 0,
                behavior: "smooth",
            }});
        }});

        updateEvents();
    </script>
</body>
</html>
"""

    Path(path).write_text(html, encoding="utf-8")