from .models import Event

from html import escape
from pathlib import Path


def generate_html(events: list[Event], path: str, area: str) -> None:
    sorted_events = sorted(
        events,
        key=lambda event: (
            event.numerical_month if event.numerical_month is not None else 99,
            event.numerical_date if event.numerical_date is not None else 99,
            event.date,
        ),
    )

    dated_events = [
        event
        for event in sorted_events
        if event.numerical_month is not None and event.numerical_date is not None
    ]

    month_names = {
        1: "January",
        2: "February",
        3: "March",
        4: "April",
        5: "May",
        6: "June",
        7: "July",
        8: "August",
        9: "September",
        10: "October",
        11: "November",
        12: "December",
    }

    if len(dated_events) >= 2:
        first_event = dated_events[0]
        last_event = dated_events[-1]
        time_span = (
            f"{month_names.get(first_event.numerical_month, str(first_event.numerical_month))} "
            f"{first_event.numerical_date} – "
            f"{month_names.get(last_event.numerical_month, str(last_event.numerical_month))} "
            f"{last_event.numerical_date}"
        )
    elif len(dated_events) == 1:
        only_event = dated_events[0]
        time_span = (
            f"{month_names.get(only_event.numerical_month, str(only_event.numerical_month))} "
            f"{only_event.numerical_date}"
        )
    else:
        time_span = "Time span unavailable"

    all_genres = sorted(
        {
            genre.strip()
            for event in sorted_events
            for genre in event.band_genre
            if genre.strip()
        },
        key=str.lower,
    )

    def render_genres(genres: list[str]) -> str:
        if not genres:
            return '<span class="muted">No genre info</span>'

        return "".join(
            f'<span class="genre-tag">{escape(genre)}</span>' for genre in genres
        )

    def render_genre_filters(genres: list[str]) -> str:
        if not genres:
            return '<span class="muted">No genre filters available</span>'

        return "".join(f"""
            <span class="filter-chip-group">
                <button
                    class="filter-chip include-chip"
                    type="button"
                    data-filter-mode="include"
                    data-genre="{escape(genre.lower())}"
                    title="Include {escape(genre)}"
                >
                    + {escape(genre)}
                </button>

                <button
                    class="filter-chip exclude-chip"
                    type="button"
                    data-filter-mode="exclude"
                    data-genre="{escape(genre.lower())}"
                    title="Exclude {escape(genre)}"
                    aria-label="Exclude {escape(genre)}"
                >
                    −
                </button>
            </span>
            """ for genre in genres)

    def render_event(event: Event) -> str:
        warning_html = ""

        if event.band_details_trustworthy is False:
            warning_html = """
            <div class="warning">
                ⚠️ Genre and info were generated by an LLM. This one is likely incorrect,
                so be careful and double check.
            </div>
            """

        band_info = (
            escape(event.band_info)
            if event.band_info.strip()
            else '<span class="muted">No band info available</span>'
        )

        genre_data = "|".join(
            genre.strip().lower() for genre in event.band_genre if genre.strip()
        )

        return f"""
        <article class="event-card" data-genres="{escape(genre_data)}">
            <div class="event-header">
                <div>
                    <h2>{escape(event.band)}</h2>
                    <p class="venue">{escape(event.venue)}</p>
                </div>

                <a class="event-link" href="{escape(event.link)}" target="_blank" rel="noopener noreferrer">
                    View event
                </a>
            </div>

            <p class="date">☽ {escape(event.date)}</p>

            <div class="genres">
                {render_genres(event.band_genre)}
            </div>

            <p class="band-info">{band_info}</p>

            {warning_html}
        </article>
        """

    events_html = "\n".join(render_event(event) for event in sorted_events)
    filters_html = render_genre_filters(all_genres)

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Upcoming Events</title>

    <style>
        * {{
            box-sizing: border-box;
        }}

        :root {{
            --ink: #26231f;
            --soft-ink: #5b534b;
            --muted-ink: #8a7f73;

            --paper: #eee7dc;
            --paper-deep: #e3d8c9;
            --card: #f8f1e7;
            --card-soft: #fbf7ef;

            --sepia: #8b6f47;
            --sepia-dark: #57452f;
            --ash-blue: #596877;
            --ash-blue-dark: #3e4a56;
            --wine: #7b3f48;
            --rust: #9a5a3c;

            --border: #cdbfae;
            --border-dark: #a9957f;
            --shadow: rgba(52, 43, 34, 0.15);
        }}

        body {{
            margin: 0;
            font-family: Georgia, "Times New Roman", Times, serif;
            background:
                radial-gradient(circle at 12% 8%, rgba(123, 63, 72, 0.16), transparent 28rem),
                radial-gradient(circle at 84% 18%, rgba(89, 104, 119, 0.18), transparent 30rem),
                linear-gradient(180deg, #d8cbbc 0%, var(--paper) 34%, #e9dfd2 100%);
            color: var(--ink);
            line-height: 1.58;
            font-size: 15px;
        }}

        body::before {{
            content: "";
            position: fixed;
            inset: 0;
            pointer-events: none;
            opacity: 0.28;
            background-image:
                linear-gradient(rgba(70, 55, 40, 0.045) 1px, transparent 1px),
                linear-gradient(90deg, rgba(70, 55, 40, 0.035) 1px, transparent 1px);
            background-size: 42px 42px;
        }}

        header {{
            position: relative;
            overflow: hidden;
            padding: 46px 20px 42px;
            background:
                linear-gradient(135deg, rgba(38, 35, 31, 0.96), rgba(62, 74, 86, 0.94)),
                radial-gradient(circle at top, rgba(205, 191, 174, 0.25), transparent 28rem);
            color: #f4eadc;
            text-align: center;
            border-bottom: 1px solid rgba(205, 191, 174, 0.42);
            box-shadow: 0 18px 40px rgba(38, 35, 31, 0.18);
        }}

        header::after {{
            content: "";
            position: absolute;
            left: 50%;
            bottom: 20px;
            width: min(460px, 70vw);
            height: 1px;
            transform: translateX(-50%);
            background: linear-gradient(90deg, transparent, rgba(244, 234, 220, 0.55), transparent);
        }}

        header h1 {{
            position: relative;
            margin: 0;
            font-size: clamp(1.8rem, 4vw, 2.55rem);
            letter-spacing: 0.08em;
            font-weight: 500;
            text-transform: uppercase;
        }}

        header p {{
            position: relative;
            margin: 8px 0 0;
            color: #d6c9ba;
            font-size: 0.98rem;
            font-style: italic;
        }}

        .time-span {{
            position: relative;
            display: inline-flex;
            align-items: center;
            gap: 10px;
            margin-top: 18px;
            padding: 9px 18px;
            border-radius: 999px;
            color: #eadfce;
            background: rgba(244, 234, 220, 0.08);
            border: 1px solid rgba(244, 234, 220, 0.28);
            font-size: 0.9rem;
            font-style: italic;
            letter-spacing: 0.04em;
        }}

        .time-span::before,
        .time-span::after {{
            content: "✦";
            color: rgba(244, 234, 220, 0.58);
            font-size: 0.72rem;
        }}

        main {{
            max-width: 1180px;
            margin: 0 auto;
            padding: 34px 24px 64px;
        }}

        .toolbar {{
            background:
                linear-gradient(180deg, rgba(251, 247, 239, 0.95), rgba(244, 236, 224, 0.94));
            border: 1px solid var(--border);
            border-left: 4px solid var(--ash-blue);
            border-radius: 18px;
            padding: 22px;
            margin-bottom: 30px;
            box-shadow:
                0 16px 36px rgba(52, 43, 34, 0.10),
                inset 0 1px 0 rgba(255, 255, 255, 0.55);
        }}

        .toolbar-top {{
            display: flex;
            justify-content: space-between;
            align-items: center;
            gap: 16px;
            margin-bottom: 14px;
            padding-bottom: 13px;
            border-bottom: 1px solid rgba(169, 149, 127, 0.42);
        }}

        .toolbar h2 {{
            margin: 0;
            color: var(--sepia-dark);
            font-size: 1.05rem;
            line-height: 1.25;
            font-weight: 500;
            letter-spacing: 0.04em;
            text-transform: uppercase;
        }}

        .result-count {{
            margin: 0;
            color: var(--muted-ink);
            font-size: 0.92rem;
            white-space: nowrap;
            font-style: italic;
        }}

        .filter-row {{
            display: flex;
            flex-wrap: wrap;
            gap: 9px;
        }}

        .filter-chip-group {{
            display: inline-flex;
            align-items: stretch;
        }}

        .filter-chip,
        .clear-button {{
            appearance: none;
            border: 1px solid #c6b7a5;
            border-radius: 999px;
            background: rgba(248, 241, 231, 0.86);
            color: var(--sepia-dark);
            padding: 7px 12px;
            font-family: Georgia, "Times New Roman", Times, serif;
            font-size: 0.84rem;
            font-weight: 700;
            line-height: 1.25;
            cursor: pointer;
        }}

        .filter-chip:hover,
        .clear-button:hover {{
            background: #ece1d2;
            color: var(--wine);
            border-color: var(--wine);
        }}

        .filter-chip-group .include-chip {{
            border-top-right-radius: 0;
            border-bottom-right-radius: 0;
        }}

        .filter-chip-group .exclude-chip {{
            border-top-left-radius: 0;
            border-bottom-left-radius: 0;
            margin-left: -1px;
            padding-inline: 10px;
        }}

        .filter-chip.include-active {{
            background: var(--ash-blue-dark);
            border-color: var(--ash-blue-dark);
            color: #f8f1e7;
        }}

        .filter-chip.exclude-active {{
            background: var(--wine);
            border-color: var(--wine);
            color: #f8f1e7;
        }}

        .filter-chip.include-active:hover {{
            background: var(--ash-blue-dark);
            border-color: var(--ash-blue-dark);
            color: #f8f1e7;
        }}

        .filter-chip.exclude-active:hover {{
            background: var(--wine);
            border-color: var(--wine);
            color: #f8f1e7;
        }}

        .clear-button {{
            background: rgba(255, 252, 246, 0.8);
            color: var(--muted-ink);
        }}

        .event-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(420px, 1fr));
            gap: 30px;
            align-items: start;
        }}

        .event-card {{
            position: relative;
            overflow: hidden;
            background:
                linear-gradient(180deg, rgba(251, 247, 239, 0.98), rgba(246, 238, 226, 0.96));
            border-radius: 18px;
            padding: 26px;
            box-shadow:
                0 18px 46px rgba(52, 43, 34, 0.12),
                0 2px 8px rgba(52, 43, 34, 0.06);
            border: 1px solid var(--border);
            border-top: 3px double var(--border-dark);
        }}

        .event-card::before {{
            content: "";
            position: absolute;
            top: 0;
            left: 22px;
            width: 1px;
            height: 100%;
            background: rgba(123, 63, 72, 0.16);
        }}

        .event-card::after {{
            content: "";
            position: absolute;
            inset: 10px;
            border: 1px solid rgba(169, 149, 127, 0.24);
            border-radius: 13px;
            pointer-events: none;
        }}

        .event-card:hover {{
            transform: translateY(-2px);
            box-shadow:
                0 26px 60px rgba(52, 43, 34, 0.16),
                0 4px 12px rgba(52, 43, 34, 0.08);
            transition: 160ms ease;
        }}

        .event-card.hidden {{
            display: none;
        }}

        .event-header {{
            position: relative;
            z-index: 1;
            display: flex;
            justify-content: space-between;
            gap: 18px;
            align-items: flex-start;
            margin-bottom: 16px;
            padding-left: 14px;
        }}

        h2 {{
            margin: 0;
            font-size: 1.26rem;
            line-height: 1.25;
            letter-spacing: 0.01em;
            color: var(--ink);
            font-weight: 600;
        }}

        .venue {{
            margin: 7px 0 0;
            color: var(--soft-ink);
            font-weight: 700;
            line-height: 1.42;
        }}

        .date {{
            position: relative;
            z-index: 1;
            display: inline-flex;
            align-items: center;
            gap: 6px;
            margin: 0 0 16px 14px;
            padding: 7px 11px;
            border-radius: 999px;
            background: rgba(227, 216, 201, 0.58);
            color: var(--ash-blue-dark);
            border: 1px solid rgba(169, 149, 127, 0.56);
            font-size: 0.9rem;
            font-style: italic;
        }}

        .event-link {{
            flex: 0 0 auto;
            white-space: nowrap;
            text-decoration: none;
            background: var(--wine);
            color: #fbf4ea;
            padding: 9px 14px;
            border-radius: 999px;
            font-size: 0.82rem;
            font-weight: 750;
            box-shadow: 0 8px 18px rgba(123, 63, 72, 0.22);
            border: 1px solid rgba(255, 255, 255, 0.24);
        }}

        .event-link:hover {{
            background: #63323a;
        }}

        .genres {{
            position: relative;
            z-index: 1;
            display: flex;
            flex-wrap: wrap;
            gap: 8px;
            margin: 2px 0 18px 14px;
        }}

        .genre-tag {{
            display: inline-block;
            padding: 5px 10px;
            border-radius: 999px;
            background: rgba(89, 104, 119, 0.12);
            color: var(--ash-blue-dark);
            border: 1px solid rgba(89, 104, 119, 0.22);
            font-size: 0.79rem;
            font-weight: 700;
            line-height: 1.35;
        }}

        .band-info {{
            position: relative;
            z-index: 1;
            margin: 0;
            padding-left: 14px;
            color: var(--soft-ink);
            font-size: 0.93rem;
            line-height: 1.7;
        }}

        .warning {{
            position: relative;
            z-index: 1;
            margin: 18px 0 0 14px;
            padding: 12px 14px;
            border-radius: 14px;
            background: rgba(154, 90, 60, 0.10);
            border: 1px solid rgba(154, 90, 60, 0.38);
            color: #75402e;
            font-size: 0.84rem;
            font-weight: 700;
            line-height: 1.45;
        }}

        .muted {{
            color: var(--muted-ink);
            font-style: italic;
        }}

        .empty-state {{
            display: none;
            margin-top: 32px;
            padding: 30px;
            border-radius: 18px;
            background: rgba(251, 247, 239, 0.95);
            border: 1px dashed var(--border-dark);
            color: var(--muted-ink);
            text-align: center;
            font-size: 1rem;
            font-style: italic;
        }}

        .empty-state.visible {{
            display: block;
        }}

        @media (max-width: 960px) {{
            main {{
                max-width: 760px;
            }}

            .event-grid {{
                grid-template-columns: 1fr;
            }}
        }}

        @media (max-width: 560px) {{
            body {{
                font-size: 14px;
            }}

            header {{
                padding: 34px 16px 30px;
            }}

            main {{
                padding: 22px 14px 48px;
            }}

            .toolbar {{
                padding: 18px;
                border-radius: 16px;
            }}

            .toolbar-top {{
                flex-direction: column;
                align-items: flex-start;
                gap: 6px;
            }}

            .event-card {{
                padding: 22px;
                border-radius: 16px;
            }}

            .event-card::before {{
                left: 16px;
            }}

            .event-header {{
                flex-direction: column;
                gap: 12px;
                padding-left: 8px;
            }}

            .event-link {{
                width: fit-content;
            }}

            .date,
            .genres,
            .band-info,
            .warning {{
                margin-left: 8px;
                padding-left: 0;
            }}

            h2 {{
                font-size: 1.16rem;
            }}

            .time-span {{
                font-size: 0.84rem;
                padding: 8px 14px;
            }}
        }}
    </style>
</head>

<body>
    <header>
        <h1>Upcoming Events in {escape(area)}</h1>
        <p>{len(sorted_events)} event{"s" if len(sorted_events) != 1 else ""}</p>
        <p>Content generated by LLM. Please double check for correctness.</p>
        <div class="time-span">Time span: {escape(time_span)}</div>
    </header>

    <main>
        <section class="toolbar" aria-label="Genre filters">
            <div class="toolbar-top">
                <h2>Include or exclude genres</h2>
                <p class="result-count">
                    Showing <span id="visible-count">{len(sorted_events)}</span> of {len(sorted_events)}
                </p>
            </div>

            <div class="filter-row">
                <button class="clear-button" type="button" id="clear-filters">
                    Show all
                </button>
                {filters_html}
            </div>
        </section>

        <section class="event-grid" id="event-grid">
            {events_html}
        </section>

        <div class="empty-state" id="empty-state">
            No events match the selected genre filters.
        </div>
    </main>

    <script>
        const filterButtons = Array.from(document.querySelectorAll(".filter-chip"));
        const clearButton = document.getElementById("clear-filters");
        const cards = Array.from(document.querySelectorAll(".event-card"));
        const visibleCount = document.getElementById("visible-count");
        const emptyState = document.getElementById("empty-state");

        const includedGenres = new Set();
        const excludedGenres = new Set();

        function getCardGenres(card) {{
            if (!card.dataset.genres) {{
                return [];
            }}

            return card.dataset.genres
                .split("|")
                .map((genre) => genre.trim())
                .filter(Boolean);
        }}

        function updateEvents() {{
            let shown = 0;

            cards.forEach((card) => {{
                const genres = getCardGenres(card);

                const matchesIncluded =
                    includedGenres.size === 0 ||
                    genres.some((genre) => includedGenres.has(genre));

                const matchesExcluded =
                    genres.some((genre) => excludedGenres.has(genre));

                const shouldShow = matchesIncluded && !matchesExcluded;

                card.classList.toggle("hidden", !shouldShow);

                if (shouldShow) {{
                    shown += 1;
                }}
            }});

            visibleCount.textContent = shown;
            emptyState.classList.toggle("visible", shown === 0);
        }}

        function getPairedButton(mode, genre) {{
            const pairedMode = mode === "include" ? "exclude" : "include";

            return document.querySelector(
                `.filter-chip[data-filter-mode="${{pairedMode}}"][data-genre="${{CSS.escape(genre)}}"]`
            );
        }}

        filterButtons.forEach((button) => {{
            button.addEventListener("click", () => {{
                const genre = button.dataset.genre;
                const mode = button.dataset.filterMode;

                if (!genre || !mode) {{
                    return;
                }}

                const isInclude = mode === "include";
                const activeSet = isInclude ? includedGenres : excludedGenres;
                const oppositeSet = isInclude ? excludedGenres : includedGenres;
                const activeClass = isInclude ? "include-active" : "exclude-active";
                const oppositeClass = isInclude ? "exclude-active" : "include-active";

                if (activeSet.has(genre)) {{
                    activeSet.delete(genre);
                    button.classList.remove(activeClass);
                }} else {{
                    activeSet.add(genre);
                    oppositeSet.delete(genre);
                    button.classList.add(activeClass);

                    const pairedButton = getPairedButton(mode, genre);

                    if (pairedButton) {{
                        pairedButton.classList.remove(oppositeClass);
                    }}
                }}

                updateEvents();
            }});
        }});

        clearButton.addEventListener("click", () => {{
            includedGenres.clear();
            excludedGenres.clear();

            filterButtons.forEach((button) => {{
                button.classList.remove("include-active");
                button.classList.remove("exclude-active");
            }});

            updateEvents();
        }});
    </script>
</body>
</html>
"""

    Path(path).write_text(html, encoding="utf-8")
